version: '3.8'

services:
  backend:
    image: kienghok/backend_app:v1.1
    container_name: backend_app
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: kienghok/frontend_app:v1.1
    container_name: frontend_app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://54.198.237.218:8000
    restart: always